version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=myexpenses
      - DB_SSLMODE=disable
      - PORT=8080
    depends_on:
      - postgres
    networks:
      - myexpenses-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myexpenses
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myexpenses-network

volumes:
  postgres_data:

networks:
  myexpenses-network:
    driver: bridge
